// Stub for aws-exports.js, which is generated by `amplify push` and gitignored.
// Tests that need specific values should override this with jest.mock().
const awsconfig = {};
export default awsconfig;
