// AUTO-GENERATED by scripts/sync-lambda-graphql.js
// Do not edit by hand — run `npm run sync-lambda-graphql` after any schema change.
// Source: src/graphql/mutations.js and src/graphql/queries.js

const createChat = /* GraphQL */ `
  mutation CreateChat(
    $input: CreateChatInput!
    $condition: ModelChatConditionInput
  ) {
    createChat(input: $input, condition: $condition) {
      id
      message
      message_in_thread
      user_email
      speaker_name
      thread_id
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;

const updatePersonalities = /* GraphQL */ `
  mutation UpdatePersonalities(
    $input: UpdatePersonalitiesInput!
    $condition: ModelPersonalitiesConditionInput
  ) {
    updatePersonalities(input: $input, condition: $condition) {
      id
      name_1
      personality_1
      name_2
      personality_2
      image_1
      image_2
      user_email
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;

const listPersonalities = /* GraphQL */ `
  query ListPersonalities(
    $filter: ModelPersonalitiesFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listPersonalities(filter: $filter, limit: $limit, nextToken: $nextToken) {
      items {
        id
        name_1
        personality_1
        name_2
        personality_2
        image_1
        image_2
        user_email
        createdAt
        updatedAt
        owner
        __typename
      }
      nextToken
      __typename
    }
  }
`;

const listChats = /* GraphQL */ `
  query ListChats(
    $filter: ModelChatFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listChats(filter: $filter, limit: $limit, nextToken: $nextToken) {
      items {
        id
        message
        message_in_thread
        user_email
        speaker_name
        thread_id
        createdAt
        updatedAt
        owner
        __typename
      }
      nextToken
      __typename
    }
  }
`;

module.exports = { createChat, updatePersonalities, listPersonalities, listChats };
