'use client'
import { Inter } from 'next/font/google'
import './globals.css'
import { Authenticator, Divider } from '@aws-amplify/ui-react';


const inter = Inter({ subsets: ['latin'] })
/*
export const metadata = {
  title: 'Bot Chat',
  description: 'Generated by create next app',
}
*/
export default function RootLayout({ children }) {
  return (
    <html lang="en" title="Bot Chat">
      <Authenticator.Provider hideSignUp={true}>
        <body className={inter.className}>{children}
        </body>
      </Authenticator.Provider>
    </html>
  )
}
